from Collaborator.colab import notebook

nb = notebook("output")
print(nb.read_code_cell(3))
print(nb.read_text_cell(-1))
print(nb.read_code_cell(-100))

input()
nb.insert_text_cell("Hello Increment!", 0)
print(nb.read_cell(0))
print(nb.read_text_cell(0))
nb.insert_text_cell("Hello Again!", 0)
print(nb.read_text_cell(1))
input()
print(nb.read_cell(0))
nb.delete_cell(0)
print(nb.read_cell(0))
nb.delete_cell(0)
print(nb.read_cell(0))

nb.save_to_file("output")
input()
nb.insert_code_cell("""print("Hello Coding!")""", 0)
print(nb.run_cell(0))
print(nb.get_cell_outputs(0))
input()
print(nb.get_cell_type(0))
print(nb.get_cell_type(1))
print(nb.get_cell_type(2))
print(nb.merge_cells(0,1))
print(nb.merge_cells(1,2))
input()
print(nb.get_cell_type(0))
print(nb.get_cell_type(1))
print(nb.get_cell_type(2))
nb.move_cell(0,1)
input()
print(nb.get_cell_type(0))
print(nb.get_cell_type(1))
print(nb.get_cell_type(2))
